const SUPABASE_URL="https://cevylpnoexugwgygvtgu.supabase.co";
const SUPABASE_KEY="sb_publishable_AdfM5y6RqvF3tbvEVzDZSg_JuGTQLD-";
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
async function getSession(){return (await db.auth.getSession()).data.session}
async function auth(){const s=await getSession();if(!s){location.href="../login.html?returnTo="+encodeURIComponent(location.pathname+location.search);return null}return s.user}
async function membership(u){if(!u?.id)return null;return (await db.from("crowspace_memberships").select("status,membership_plans(plan_key,name,level,description,features)").eq("user_id",u.id).maybeSingle()).data||null}
async function ensureMember(u){if(!u?.id)return null;let r=await db.from("crowspace_members").select("*").eq("user_id",u.id).maybeSingle();if(r.data)return r.data;const name=u.user_metadata?.full_name||u.user_metadata?.name||u.email?.split("@")[0]||"Crow",username=(u.user_metadata?.username||"crow-"+u.id.slice(0,8)).toLowerCase().replace(/[^a-z0-9_-]/g,"").slice(0,40);r=await db.from("crowspace_members").insert({user_id:u.id,display_name:name,username,bio:"",is_public:true}).select("*").single();return r.data||(await db.from("crowspace_members").select("*").eq("user_id",u.id).maybeSingle()).data||null}
async function profile(u){if(!u?.id)return null;let r=await db.from("crowspace_profiles").select("*").eq("user_id",u.id).maybeSingle();if(r.data)return r.data;const m=await ensureMember(u),name=m?.display_name||u.email?.split("@")[0]||"Crow",username=m?.username||"crow-"+u.id.slice(0,8);await db.from("crowspace_profiles").insert({user_id:u.id,username,display_name:name,bio:m?.bio||"",profile_visibility:"public"});return (await db.from("crowspace_profiles").select("*").eq("user_id",u.id).maybeSingle()).data||null}
function shell(active){if(document.querySelector(".top"))return;document.body.insertAdjacentHTML("afterbegin",'<header class="top"><div class="wrap nav"><a class="logo" href="index.html">CROW<b>SPACE</b></a><button class="menu-btn" id="menu-btn">☰</button><nav class="links" id="nav-links"><a class="'+(active==="space"?"active":"")+'" href="my-space.html">My Space</a><a class="'+(active==="feed"?"active":"")+'" href="feed.html">Feed</a><a class="'+(active==="discover"?"active":"")+'" href="discover.html">Discover</a><a class="'+(active==="groups"?"active":"")+'" href="groups.html">Groups</a><a class="'+(active==="friends"?"active":"")+'" href="friends.html">Friends</a><a class="'+(active==="messages"?"active":"")+'" href="messages.html">Messages</a><a class="'+(active==="projects"?"active":"")+'" href="projects.html">Projects</a><a class="'+(active==="notifications"?"active":"")+'" href="notifications.html">Activity <span id="nav-count" class="nav-count"></span></a><a href="search.html">Search</a><a class="'+(active==="settings"?"active":"")+'" href="settings.html">Settings</a></nav><div class="spacer"></div><a class="btn small" href="../membership.html">MEMBERSHIP</a><a class="btn red small" href="../login.html">ACCOUNT</a></div></header>');$("#menu-btn")?.addEventListener("click",()=>$("#nav-links")?.classList.toggle("open"))}
async function navCount(u){if(!u)return;const r=await db.from("crowspace_notifications").select("id",{count:"exact",head:true}).eq("user_id",u.id).eq("is_read",false);if($("#nav-count"))$("#nav-count").textContent=r.count||""}
async function renderMembership(target,u){const el=typeof target==="string"?$(target):target;if(!el)return;u=u||await auth();if(!u)return;const m=await membership(u);el.innerHTML='<div class="membership-badge"><div class="membership-mark">CR</div><div class="membership-info"><strong>UNIVERSAL CROWRULES MEMBER</strong><span>'+esc(m?.membership_plans?.name||"CROW")+'</span><small>Status: '+esc(m?.status||"active")+'</small></div><a class="btn small" href="../membership.html">MANAGE</a></div>'}
function avatar(url,name,cls="avatar"){return '<img class="'+cls+'" src="'+esc(url||"")+'" alt="'+esc(name||"Crow")+'" loading="lazy" onerror="this.style.visibility=\'hidden\'">'}
async function renderFeed(box,u,limit=40,authorId=null){let q=db.from("crowspace_posts").select("id,author_id,body,media_url,like_count,comment_count,created_at").eq("visibility","public").eq("status","published").order("created_at",{ascending:false}).limit(limit);if(authorId)q=q.eq("author_id",authorId);const r=await q;if(r.error){box.innerHTML='<div class="empty">CrowFeed error: '+esc(r.error.message)+'</div>';return}const posts=r.data||[],ids=[...new Set(posts.map(x=>x.author_id))],ps=ids.length?(await db.from("crowspace_members").select("id,display_name,username,avatar_url").in("id",ids)).data||[]:[],map=Object.fromEntries(ps.map(x=>[x.id,x]));let liked=new Set();if(u&&posts.length){const l=await db.from("crowspace_likes").select("post_id").eq("user_id",u.id).in("post_id",posts.map(x=>x.id));liked=new Set((l.data||[]).map(x=>x.post_id))}box.innerHTML=posts.map(x=>{const p=map[x.author_id]||{};return '<article class="card post"><div class="profile-head">'+avatar(p.avatar_url,p.display_name||p.username,"avatar mini")+'<div><strong>'+esc(p.display_name||p.username||"Crow")+'</strong><div class="meta">@'+esc(p.username||"crow")+' · '+new Date(x.created_at).toLocaleString()+'</div></div></div><p>'+esc(x.body)+'</p>'+(x.media_url?'<img class="post-media" src="'+esc(x.media_url)+'" alt="" loading="lazy">':"")+'<div class="post-actions"><button class="text-btn '+(liked.has(x.id)?"liked":"")+'" data-like="'+x.id+'">♥ <span>'+Number(x.like_count||0)+'</span></button><button class="text-btn" data-comments="'+x.id+'">💬 <span>'+Number(x.comment_count||0)+'</span></button></div><div class="comments" id="comments-'+x.id+'"></div></article>'}).join("")||'<div class="empty">No public posts yet. Be the first to share something.</div>';box.querySelectorAll("[data-like]").forEach(b=>b.onclick=async()=>{if(!u){location.href="../login.html";return}const z=await db.rpc("crowspace_toggle_like",{target_post_id:b.dataset.like});if(z.error){alert(z.error.message);return}b.classList.toggle("liked",z.data?.liked);b.querySelector("span").textContent=z.data?.count??0});box.querySelectorAll("[data-comments]").forEach(b=>b.onclick=()=>loadComments(b.dataset.comments,u))}
async function loadComments(id,u){const box=$("#comments-"+id);if(!box)return;const q=await db.from("crowspace_comments").select("author_id,content,created_at").eq("post_id",id).order("created_at");if(q.error){box.innerHTML='<div class="meta">'+esc(q.error.message)+'</div>';return}const ids=[...new Set((q.data||[]).map(x=>x.author_id))],ps=ids.length?(await db.from("crowspace_members").select("id,display_name,username").in("id",ids)).data||[]:[],map=Object.fromEntries(ps.map(x=>[x.id,x]));box.innerHTML=(q.data||[]).map(x=>'<div class="comment"><strong>'+esc(map[x.author_id]?.display_name||map[x.author_id]?.username||"Crow")+'</strong> '+esc(x.content)+'<div class="meta">'+new Date(x.created_at).toLocaleString()+'</div></div>').join("")||'<div class="meta">No comments yet.</div>';if(u)box.insertAdjacentHTML("beforeend",'<div class="comment-form"><input id="comment-'+id+'" maxlength="1000" placeholder="Add a comment"><button class="btn small red" id="send-comment-'+id+'">POST</button></div>');$("#send-comment-"+id)?.addEventListener("click",async()=>{const member=await ensureMember(u),input=$("#comment-"+id),z=await db.from("crowspace_comments").insert({post_id:id,author_id:member.id,content:input.value.trim()});if(z.error)alert(z.error.message);else loadComments(id,u)})}
async function feed(){return renderFeed($("#feed-list"),(await getSession())?.user)}
document.addEventListener("DOMContentLoaded",async()=>{shell(document.body.dataset.active||"");const s=await getSession();if(s)navCount(s.user)});