const SUPABASE_URL="https://cevylpnoexugwgygvtgu.supabase.co";
const SUPABASE_KEY="sb_publishable_AdfM5y6RqvF3tbvEVzDZSg_JuGTQLD-";
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const safeUrl=s=>{try{const u=new URL(String(s||""),location.href);return ["http:","https:"].includes(u.protocol)?u.href:""}catch{return""}};
async function getSession(){return (await db.auth.getSession()).data.session}
async function auth(){const s=await getSession();if(!s){location.href="../login.html?returnTo="+encodeURIComponent(location.pathname+location.search);return null}return s.user}
async function membership(u){if(!u?.id)return null;const r=await db.from("crowspace_memberships").select("status,membership_plans(plan_key,name,level,description,features)").eq("user_id",u.id).maybeSingle();return r.data||null}
async function ensureMember(u){if(!u?.id)return null;let r=await db.from("crowspace_members").select("*").eq("user_id",u.id).maybeSingle();if(r.data)return r.data;const name=u.user_metadata?.full_name||u.user_metadata?.name||u.email?.split("@")[0]||"Crow";let username=(u.user_metadata?.username||"crow-"+u.id.slice(0,8)).toLowerCase().replace(/[^a-z0-9_-]/g,"").slice(0,40)||"crow-"+u.id.slice(0,8);r=await db.from("crowspace_members").insert({user_id:u.id,display_name:name,username,bio:"",is_public:true}).select("*").single();return r.data||(await db.from("crowspace_members").select("*").eq("user_id",u.id).maybeSingle()).data||null}
async function profile(u){if(!u?.id)return null;let r=await db.from("crowspace_profiles").select("*").eq("user_id",u.id).maybeSingle();if(r.data)return r.data;const m=await ensureMember(u),name=m?.display_name||u.email?.split("@")[0]||"Crow",username=m?.username||"crow-"+u.id.slice(0,8);await db.from("crowspace_profiles").upsert({user_id:u.id,username,display_name:name,bio:m?.bio||"",profile_visibility:"public"});return (await db.from("crowspace_profiles").select("*").eq("user_id",u.id).maybeSingle()).data||null}
function shell(active){if(document.querySelector(".top"))return;document.body.insertAdjacentHTML("afterbegin",'<header class="top"><div class="wrap nav"><a class="logo" href="index.html" aria-label="CrowSpace home">CROW<b>SPACE</b></a><button class="menu-btn" id="menu-btn" type="button" aria-label="Open menu" aria-expanded="false">☰</button><nav class="links" id="nav-links"><a class="'+(active==="space"?"active":"")+'" href="my-space.html">My Space</a><a class="'+(active==="feed"?"active":"")+'" href="feed.html">Feed</a><a class="'+(active==="discover"?"active":"")+'" href="discover.html">Discover</a><a class="'+(active==="groups"?"active":"")+'" href="groups.html">Groups</a><a class="'+(active==="friends"?"active":"")+'" href="friends.html">Friends</a><a class="'+(active==="messages"?"active":"")+'" href="messages.html">Messages</a><a class="'+(active==="projects"?"active":"")+'" href="projects.html">Projects</a><a class="'+(active==="notifications"?"active":"")+'" href="notifications.html">Activity <span id="nav-count" class="nav-count"></span></a><a class="'+(active==="search"?"active":"")+'" href="search.html">Search</a><a class="'+(active==="settings"?"active":"")+'" href="settings.html">Settings</a></nav><div class="spacer"></div><a class="btn small" href="../membership.html">MEMBERSHIP</a><a class="btn red small" href="../login.html">ACCOUNT</a></div></header>');$("#menu-btn")?.addEventListener("click",()=>{const n=$("#nav-links"),b=$("#menu-btn");n?.classList.toggle("open");b?.setAttribute("aria-expanded",n?.classList.contains("open")?"true":"false")})}
async function navCount(u){if(!u)return;const r=await db.from("crowspace_notifications").select("id",{count:"exact",head:true}).eq("user_id",u.id).eq("is_read",false);if($("#nav-count"))$("#nav-count").textContent=r.error?"":(r.count||"")}
async function renderMembership(target,u){const el=typeof target==="string"?$(target):target;if(!el)return;u=u||await auth();if(!u)return;const m=await membership(u);el.innerHTML='<div class="membership-badge"><div class="membership-mark">CR</div><div class="membership-info"><strong>UNIVERSAL CROWRULES MEMBER</strong><span>'+esc(m?.membership_plans?.name||"CROW")+'</span><small>Status: '+esc(m?.status||"active")+'</small></div><a class="btn small" href="../membership.html">MANAGE</a></div>'}
function avatar(url,name,cls="avatar"){const src=safeUrl(url);return '<img class="'+esc(cls)+'" src="'+esc(src)+'" alt="'+esc(name||"Crow")+'" loading="lazy" onerror="this.removeAttribute(\'src\');this.style.visibility=\'hidden\'">'}
async function renderFeed(box,u,limit=40,authorId=null){if(!box)return;let q=db.from("crowspace_posts").select("id,author_id,body,media_url,media_type,like_count,comment_count,created_at").eq("visibility","public").eq("status","published").order("created_at",{ascending:false}).limit(Math.min(Math.max(Number(limit)||40,1),100));if(authorId)q=q.eq("author_id",authorId);const r=await q;if(r.error){box.innerHTML='<div class="empty">CrowFeed error: '+esc(r.error.message)+'</div>';return}return renderPostRows(box,r.data||[],u)}
async function renderPostRows(box,posts,u,opts={}){const ids=[...new Set(posts.map(x=>x.author_id))],ps=ids.length?(await db.from("crowspace_members").select("id,display_name,username,avatar_url").in("id",ids)).data||[]:[],map=Object.fromEntries(ps.map(x=>[x.id,x]));let liked=new Set(),saved=new Set(),reactions={};if(u&&posts.length){const ids2=posts.map(x=>x.id);const [l,b,rx]=await Promise.all([db.from("crowspace_likes").select("post_id").eq("user_id",u.id).in("post_id",ids2),db.from("crowspace_bookmarks").select("post_id").eq("user_id",u.id).in("post_id",ids2),db.from("crowspace_post_reactions").select("post_id,reaction").eq("user_id",u.id).in("post_id",ids2)]);liked=new Set((l.data||[]).map(x=>x.post_id));saved=new Set((b.data||[]).map(x=>x.post_id));(rx.data||[]).forEach(x=>reactions[x.post_id]=x.reaction)}
box.innerHTML=posts.map(x=>{const p=map[x.author_id]||{},rx=reactions[x.id],media=safeUrl(x.media_url);return '<article class="card post" data-post="'+esc(x.id)+'"><div class="profile-head">'+avatar(p.avatar_url,p.display_name||p.username,"avatar mini")+'<div><strong>'+esc(p.display_name||p.username||"Crow")+'</strong><div class="meta">@'+esc(p.username||"crow")+' · '+new Date(x.created_at).toLocaleString()+'</div></div></div><p>'+esc(x.body)+'</p>'+(media?(x.media_type==="video"?'<video class="post-media" src="'+esc(media)+'" controls preload="metadata"></video>':'<img class="post-media" src="'+esc(media)+'" alt="" loading="lazy">'):"")+'<div class="post-actions"><button class="text-btn '+(liked.has(x.id)?"liked":"")+'" data-like="'+esc(x.id)+'">♥ <span>'+Number(x.like_count||0)+'</span></button><button class="text-btn '+(rx?"liked":"")+'" data-react="'+esc(x.id)+'">✦ '+esc(rx||"React")+'</button><button class="text-btn '+(saved.has(x.id)?"liked":"")+'" data-save="'+esc(x.id)+'">🔖 <span>'+(saved.has(x.id)?"Saved":"Save")+'</span></button><button class="text-btn" data-comments="'+esc(x.id)+'">💬 <span>'+Number(x.comment_count||0)+'</span></button></div><div class="comments" id="comments-'+esc(x.id)+'"></div></article>'}).join("")||'<div class="empty">'+esc(opts.empty||"No public posts yet. Be the first to share something.")+'</div>';
box.querySelectorAll("[data-like]").forEach(b=>b.onclick=async()=>{const z=await db.rpc("crowspace_toggle_like",{target_post_id:b.dataset.like});if(z.error){alert(z.error.message);return}b.classList.toggle("liked",!!z.data?.liked);const s=b.querySelector("span");if(s)s.textContent=z.data?.count??0});
box.querySelectorAll("[data-save]").forEach(b=>b.onclick=async()=>{const z=await db.rpc("crowspace_toggle_bookmark",{target_post:b.dataset.save});if(z.error){alert(z.error.message);return}const on=!!z.data?.saved;b.classList.toggle("liked",on);const s=b.querySelector("span");if(s)s.textContent=on?"Saved":"Save"});
box.querySelectorAll("[data-react]").forEach(b=>b.onclick=async()=>{const choices=["like","love","celebrate","support","idea"],current=b.textContent.replace("✦ ","").trim(),next=choices[(choices.indexOf(current)+1)%choices.length]||choices[0];const z=await db.rpc("crowspace_toggle_reaction",{target_post:b.dataset.react,target_reaction:next});if(z.error){alert(z.error.message);return}b.classList.toggle("liked",!!z.data?.active);b.textContent="✦ "+(z.data?.active?next:"React")});
box.querySelectorAll("[data-comments]").forEach(b=>b.onclick=()=>loadComments(b.dataset.comments,u));
if(u&&posts.length)await Promise.all(posts.slice(0,10).map(x=>db.from("crowspace_post_views").upsert({user_id:u.id,post_id:x.id,viewed_at:new Date().toISOString()})))}
async function renderPostsByIds(box,u,ids){const clean=[...new Set((ids||[]).filter(Boolean))];if(!clean.length){box.innerHTML='<div class="empty">No saved posts yet. Save something from CrowFeed.</div>';return}const r=await db.from("crowspace_posts").select("id,author_id,body,media_url,media_type,like_count,comment_count,created_at").in("id",clean).eq("status","published");if(r.error){box.innerHTML='<div class="empty">'+esc(r.error.message)+'</div>';return}const order=new Map(clean.map((id,i)=>[id,i]));(r.data||[]).sort((a,b)=>(order.get(a.id)??999)-(order.get(b.id)??999));return renderPostRows(box,r.data||[],u)}
async function loadComments(id,u){const box=$("#comments-"+id);if(!box)return;const q=await db.from("crowspace_comments").select("author_id,content,created_at").eq("post_id",id).order("created_at");if(q.error){box.innerHTML='<div class="meta">'+esc(q.error.message)+'</div>';return}const ids=[...new Set((q.data||[]).map(x=>x.author_id))],ps=ids.length?(await db.from("crowspace_profiles").select("user_id,username,display_name").in("user_id",ids)).data||[]:[],map=Object.fromEntries(ps.map(x=>[x.user_id,x]));box.innerHTML=(q.data||[]).map(x=>'<div class="comment"><strong>'+esc(map[x.author_id]?.display_name||map[x.author_id]?.username||"Crow")+'</strong> '+esc(x.content)+'<div class="meta">'+new Date(x.created_at).toLocaleString()+'</div></div>').join("")||'<div class="meta">No comments yet.</div>';if(u)box.insertAdjacentHTML("beforeend",'<div class="comment-form"><input id="comment-'+esc(id)+'" maxlength="1000" placeholder="Add a comment"><button class="btn small red" id="send-comment-'+esc(id)+'" type="button">POST</button></div>');$("#send-comment-"+id)?.addEventListener("click",async()=>{const member=await ensureMember(u),input=$("#comment-"+id),body=input?.value.trim();if(!member||!body)return;const z=await db.from("crowspace_comments").insert({post_id:id,author_id:u.id,content:body});if(z.error)alert(z.error.message);else loadComments(id,u)})}
async function feed(){return renderFeed($("#feed-list"),(await getSession())?.user)}
function realtimeFeed(){if(!$("#feed-list"))return;db.channel("crowspace-live-feed-"+Math.random().toString(36).slice(2)).on("postgres_changes",{event:"*",schema:"public",table:"crowspace_posts"},()=>{getSession().then(s=>renderFeed($("#feed-list"),s?.user))}).subscribe()}
document.addEventListener("DOMContentLoaded",async()=>{shell(document.body.dataset.active||"");const s=await getSession();if(s)navCount(s.user);if(s&&$("#feed-list"))setTimeout(realtimeFeed,250)});