const CONFIG={supabaseUrl:"https://cevylpnoexugwgygvtgu.supabase.co",supabasePublishableKey:"sb_publishable_AdfM5y6RqvF3tbvEVzDZSg_JuGTQLD-",githubRepo:"crowrulesentertainment-oss/crowrulesentertainment"};let db=null;
const divisions=[["Dreamscapes","Ideas, stories, creators and rights","ACTIVE","☾"],["CrowRules TV","24/7 channels, schedule and live events","BUILDING","▤"],["Podcasting","Shows, hosts and audio distribution","NEXT","◉"],["Sports","Scores, leagues and Pick ’Em","NEXT","◆"],["Tacoma Nights","Documentary series and community","ACTIVE","▣"],["Back Deck Live","Unscripted live community show","ACTIVE","▶"],["Memorials","Celebrity and community remembrance","ACTIVE","✦"],["Yearbooks","Community and annual storytelling","PLANNED","▤"],["Records","Future music division","PLANNED","♫"],["Studios","Future production infrastructure","PLANNED","▰"],["CrowSpace","Future community platform","PLANNED","◎"],["Awards","Future Spectrum Awards","PLANNED","★"]];
const cardSets={content:[["Content","Central content records and publishing","▣"],["Announcements","Public news and launch notices","◆"],["Campaigns","Promotions, launches and outreach","◇"],["Suggestions","Community ideas and requests","✦"],["Agreements","Rights and contributor documents","▤"],["Audit Log","Administrative activity trail","⌁"]],creator:[["Creator Queue","Review creator applications and profiles","✦"],["Collaborators","Production relationships","◇"],["Credits","Track contributor credits","★"],["Opportunities","Volunteer and future paid roles","◆"],["Rights","Ownership and permissions","▣"],["Earnings","Approved project earnings records","$"]],tv:[["Channels","Manage CrowRules TV channels","▤"],["Schedule","Broadcast clock and schedule items","◷"],["Live Events","Upcoming and active events","●"],["Shows","Programming library","◇"],["On Demand","Published episodes and media","▶"],["TV Health","Broadcast configuration checks","⌁"]],media:[["YouTube","Distribution and video references","▶"],["Media Library","Images, video and audio references","▧"],["Live","Stream destinations and status","●"],["Watch Metrics","Watch seconds and history","⌁"],["Podcasting","Audio shows and episodes","◉"],["Assets","Brand and production assets","✦"]],business:[["Partnerships","Business relationships","◆"],["Sponsorships","Sponsor pipeline and packages","★"],["Donations","CrowRules support and campaigns","$"],["PayPal","Payment workflow reference","◇"],["Stripe","Payment infrastructure","▣"],["Operations","Company planning and administration","⌁"]]};
function $(id){return document.getElementById(id)}
function toast(msg){$("toast").textContent=msg;$("toast").classList.add("show");clearTimeout(window._toast);window._toast=setTimeout(()=>$("toast").classList.remove("show"),2600)}
function renderStats(){const data=[["DIVISIONS",12],["ACTIVE BUILDS",5],["PLANNED",6],["SYSTEMS",9]];$("stats").innerHTML=data.map(x=>`<div class="stat"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join("");$("memberStats").innerHTML=[["MEMBERS","—"],["CROWPOINTS","—"],["CREATORS","—"],["PENDING","—"]].map(x=>`<div class="stat"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join("");$("dreamStats").innerHTML=[["SUBMISSIONS","—"],["IN DEVELOPMENT","—"],["COLLABORATORS","—"],["PITCH READY","—"]].map(x=>`<div class="stat"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join("");$("analyticsStats").innerHTML=[["CONTENT","—"],["WATCH HOURS","—"],["ACTIVE USERS","—"],["LIVE EVENTS","—"]].map(x=>`<div class="stat"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join("")}
function renderDivisions(target="divisionGrid"){const el=$(target);el.innerHTML=divisions.map(d=>`<article class="division"><span class="status">${d[2]}</span><h3><span style="color:var(--red)">${d[3]}</span> ${d[0]}</h3><p>${d[1]}</p></article>`).join("")}
function renderCards(target,items){$(target).innerHTML=items.map(x=>`<article class="card"><div class="symbol">${x[2]}</div><h3>${x[0]}</h3><p>${x[1]}</p><button class="btn" data-toast="${x[0]} module is ready for connection">Open Module →</button></article>`).join("")}
function renderQuick(){$("quick").innerHTML=[["Publish Content"],["Review Dreamscapes"],["Manage TV"],["Check Members"],["View GitHub"],["System Health"]].map(x=>`<button data-toast="${x[0]} opened">${x[0]} →</button>`).join("")}
function renderActivity(){$("activity").innerHTML=["Admin shell deployed","Division map loaded","Security model: browser-safe mode","Supabase configuration detected","GitHub repository connected"].map(x=>`<div>${x}</div>`).join("")}
function renderEpisodes(rows=[]){const sample=rows.length?rows:[["Tacoma Nights E25","Tacoma Nights","Published","Today"],["Back Deck Live #007","Back Deck Live","Scheduled","Today"],["Back Deck Live #006","Back Deck Live","Published","Recent"],["Bird Brains #001","Bird Brains","Published","Recent"]];$("episodeTable").innerHTML=sample.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td><span class="status-pill">${r[2]}</span></td><td>${r[3]}</td></tr>`).join("")}
async function initDB(){try{if(!window.supabase||!CONFIG.supabasePublishableKey)return;db=window.supabase.createClient(CONFIG.supabaseUrl,CONFIG.supabasePublishableKey);$("connectionLabel").textContent="SUPABASE CONFIGURED";$("systemState").textContent="CONNECTED";$("systemDetail").textContent="Browser-safe publishable key detected";await loadCounts()}catch(e){console.warn(e)}}
async function countTable(table){if(!db)return null;try{const {count,error}=await db.from(table).select("*",{count:"exact",head:true});return error?null:count}catch{return null}}
async function loadCounts(){const pairs=[["cr_members","MEMBERS"],["cr_content","CONTENT"]];for(const [table,label] of pairs){const n=await countTable(table);if(n!==null){const el=[...document.querySelectorAll(".stat")].find(x=>x.querySelector("small")?.textContent===label);if(el)el.querySelector("strong").textContent=n}}}
function nav(){document.querySelectorAll("[data-section]").forEach(a=>a.addEventListener("click",e=>{e.preventDefault();const id=a.dataset.section;document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id===id));document.querySelectorAll("[data-section]").forEach(x=>x.classList.toggle("active",x===a));$("pageTitle").textContent=a.textContent.replace(/^\S+\s/,"");history.replaceState(null,"","#"+id);$("sidebar").classList.remove("open");window.scrollTo({top:0,behavior:"smooth"})}))}
document.addEventListener("click",e=>{const t=e.target.closest("[data-toast]");if(t)toast(t.dataset.toast)});
$("menu").onclick=()=>$("sidebar").classList.add("open");$("navClose").onclick=()=>$("sidebar").classList.remove("open");$("refresh").onclick=()=>{toast("Command center refreshed");location.reload()};$("ownerButton").onclick=()=>toast("Owner controls require authenticated admin session");
$("episodeRefresh").onclick=()=>{renderEpisodes();toast("Episode list refreshed")};$("episodeSearch").oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll("#episodeTable tr").forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?"":"none")};
$("year").textContent=new Date().getFullYear();renderStats();renderDivisions();renderDivisions("showsGrid");renderQuick();renderActivity();renderEpisodes();renderCards("contentCards",cardSets.content);renderCards("creatorCards",cardSets.creator);renderCards("tvCards",cardSets.tv);renderCards("mediaCards",cardSets.media);renderCards("businessCards",cardSets.business);$("pipeline").innerHTML=[["New Idea","SUBMITTED"],["Review","REVIEW"],["Development","BUILD"],["Creative Room","COLLABORATE"],["Agreement","RIGHTS"],["Pitch","PITCH"],["Production","PRODUCE"],["Released","EARNINGS"]].map(x=>`<div><b>${x[0]}</b><span>${x[1]}</span></div>`).join("");$("systemCards").innerHTML=[["GitHub",`<a href="https://github.com/${CONFIG.githubRepo}" target="_blank" rel="noopener" class="btn">Open Repository</a>`,"Source repository and deployment surface."],["Supabase",`<button class="btn" data-toast="Supabase connection check requested">Check Connection</button>`,"Database, authentication, storage and Edge Functions."],["Security","RLS + server-side roles","Never expose service-role secrets in browser code."],["Actions","GitHub Actions","Validation, deployment and scheduled maintenance."],["Backups","Repository + database","Keep source and database recovery plans separate."],["Environment","Production / staging","Use environment-specific keys and URLs."]].map(x=>`<article class="system-item"><h3>${x[0]}</h3><p>${x[2]}</p>${x[1].startsWith("<")?x[1]:`<b style="font:8px Orbitron;color:var(--cyan)">${x[1]}</b>`}</article>`).join("");nav();setTimeout(()=>$("boot").classList.add("hide"),650);initDB();